/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package manager;

import com.formdev.flatlaf.FlatDarkLaf;
import db_connection.db_connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import net.proteanit.sql.DbUtils;

/**
 *
 * @author medo4
 */
public class GetBillsInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form GetBillsInternalFrame
     */
    
    Connection con;
    db_connection c= new db_connection();
    public GetBillsInternalFrame() {
        initComponents();
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(GetBillsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            //view of internal frame modifications
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
            ui.setNorthPane(null);
            //disable Resize for internalJframe
            this.setResizable(false);
            
            
            //--------------------------------------------------------------------------------------------------------------------
            
        con= c.connect();
        try{
            String selectedColoumns = "order_id,first_name,last_name,cashier_id";
                PreparedStatement stmt = con.prepareStatement(
                    String.format("SELECT %s FROM orders join customer on customer.customer_id = orders.customer_id;",selectedColoumns));

                ResultSet resultSet = stmt.executeQuery();

                BillsInfo.setModel(DbUtils.resultSetToTableModel(resultSet));
        }
        catch(SQLException ex)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showBill = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        info_bills = new javax.swing.JTable();
        customerName = new javax.swing.JLabel();
        retCustomerName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        displayAllBills = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillsInfo = new javax.swing.JTable();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchType = new javax.swing.JComboBox<>();
        showBillButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showBill.setBackground(new java.awt.Color(51, 51, 51));

        info_bills.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 173, 252)));
        info_bills.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        info_bills.setForeground(new java.awt.Color(255, 255, 255));
        info_bills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee_id", "name", "role", "phone", "address", "gender", "sallary"
            }
        ));
        info_bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info_billsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(info_bills);

        customerName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        customerName.setForeground(new java.awt.Color(255, 255, 255));
        customerName.setText("Customer name:");

        retCustomerName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        retCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        retCustomerName.setText("Customer name:");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        displayAllBills.setBackground(new java.awt.Color(51, 51, 51));

        BillsInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 173, 252)));
        BillsInfo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BillsInfo.setForeground(new java.awt.Color(255, 255, 255));
        BillsInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bills_id", "Customer id", "Cashier_id", "Date"
            }
        ));
        BillsInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillsInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BillsInfo);

        searchLabel.setForeground(new java.awt.Color(255, 250, 244));
        searchLabel.setText("Search:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order ID", "Customer ID", "Cashier ID" }));

        showBillButton.setText("Show Bill Info");
        showBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBillButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayAllBillsLayout = new javax.swing.GroupLayout(displayAllBills);
        displayAllBills.setLayout(displayAllBillsLayout);
        displayAllBillsLayout.setHorizontalGroup(
            displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayAllBillsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(displayAllBillsLayout.createSequentialGroup()
                        .addComponent(showBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(552, 552, 552)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displayAllBillsLayout.createSequentialGroup()
                            .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(138, 138, 138)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        displayAllBillsLayout.setVerticalGroup(
            displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayAllBillsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout showBillLayout = new javax.swing.GroupLayout(showBill);
        showBill.setLayout(showBillLayout);
        showBillLayout.setHorizontalGroup(
            showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showBillLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showBillLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(displayAllBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(showBillLayout.createSequentialGroup()
                .addGroup(showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showBillLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retCustomerName))
                    .addGroup(showBillLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        showBillLayout.setVerticalGroup(
            showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayAllBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(showBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void info_billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_billsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_info_billsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        displayAllBills.setVisible(true);
        showBill.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BillsInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsInfoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BillsInfoMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if("".equals(searchField.getText().trim()))
        {
            JOptionPane.showMessageDialog(this, "Enter a value");
        }
        else
        {

            try {
                String s;
                switch (searchType.getSelectedIndex()) {
                    case 1 ->  s = "customer_id";
                    case 2 ->  s = "cashier_id";
                    default -> s = "order_id";
                }
                String selectedColoumns = "order_id,first_name,last_name,cashier_id";
                PreparedStatement stmt = con.prepareStatement(
                    String.format("SELECT %s FROM orders join customer on customer.customer_id = orders.customer_id where order_id = ?;",selectedColoumns,s));

                stmt.setString(1, searchField.getText().trim());

                ResultSet resultSet = stmt.executeQuery();

                BillsInfo.setModel(DbUtils.resultSetToTableModel(resultSet));

            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void showBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBillButtonActionPerformed
        // TODO add your handling code here:
        int row =        BillsInfo.getSelectedRow();
        if (row<0)
        {JOptionPane.showMessageDialog(null, "Please Select Order");}
        else
        {
            displayAllBills.setVisible(false);
            showBill.setVisible(true);

            String BillID =    BillsInfo.getValueAt(row, 1).toString();
            String FirstNameCustomer =    BillsInfo.getValueAt(row, 1).toString();
            String SecondNameCustomer =    BillsInfo.getValueAt(row, 2).toString();
            String orderID =    BillsInfo.getValueAt(row, 0).toString();

            retCustomerName.setText(FirstNameCustomer+" "+SecondNameCustomer);
            String selectedColoumns = "products.name,order_items.quantity,products.price,products.discount";
            PreparedStatement stmt;
            try {
                stmt = con.prepareStatement(
                    String.format("SELECT %s FROM order_items join products on order_items.product_id = products.product_id where order_id = ?;",selectedColoumns));
                stmt.setString(1, orderID);
                ResultSet resultSet = stmt.executeQuery();

                info_bills.setModel(DbUtils.resultSetToTableModel(resultSet));
            } catch (SQLException ex) {
                Logger.getLogger(GetBillsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_showBillButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillsInfo;
    private javax.swing.JLabel customerName;
    private javax.swing.JPanel displayAllBills;
    private javax.swing.JTable info_bills;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel retCustomerName;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JComboBox<String> searchType;
    private javax.swing.JPanel showBill;
    private javax.swing.JButton showBillButton;
    // End of variables declaration//GEN-END:variables
}
