/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manager;
import Products.getBills;
import Employees_info.emplyeeInfo_frame;
import Products.ViewCustomersFrame;
import billing_system_project.login;
import Products.manager_products_frame;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Products.getBills;
import java.awt.Color;
import java.sql.SQLException;


/**
 *
 * @author abdoa
 */
public class manager_frame extends javax.swing.JFrame {

    /**
     * Creates new form manager_frame
     */
    public manager_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient3 = new manager.PanelGradient();
        panelGradient5 = new manager.PanelGradient();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelGradient4 = new manager.PanelGradient();
        jLabel3 = new javax.swing.JLabel();
        panelGradient6 = new manager.PanelGradient();
        jLabel5 = new javax.swing.JLabel();
        panelGradient9 = new manager.PanelGradient();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelGradient1 = new manager.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGradient3.setBackground(new java.awt.Color(40, 184, 213));
        panelGradient3.setToolTipText("");
        panelGradient3.setColorGradient(new java.awt.Color(2, 3, 68));
        panelGradient3.setRadius(30);
        panelGradient3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGradient3MousePressed(evt);
            }
        });

        panelGradient5.setBackground(new java.awt.Color(40, 184, 213));
        panelGradient5.setToolTipText("");
        panelGradient5.setColorGradient(new java.awt.Color(2, 3, 68));
        panelGradient5.setRadius(30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Stock");
        panelGradient5.add(jLabel4);
        jLabel4.setBounds(30, 10, 60, 20);

        panelGradient3.add(panelGradient5);
        panelGradient5.setBounds(0, 0, 0, 0);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/bill.png"))); // NOI18N
        jLabel7.setText("  View Bills");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        panelGradient3.add(jLabel7);
        jLabel7.setBounds(0, 10, 250, 70);

        getContentPane().add(panelGradient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 290, 88));

        panelGradient4.setBackground(new java.awt.Color(40, 184, 213));
        panelGradient4.setForeground(new java.awt.Color(204, 153, 255));
        panelGradient4.setToolTipText("");
        panelGradient4.setColorGradient(new java.awt.Color(2, 3, 68));
        panelGradient4.setRadius(30);
        panelGradient4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGradient4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 38)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/ready-stock (1).png"))); // NOI18N
        jLabel3.setText(" View Stock");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        panelGradient4.add(jLabel3);
        jLabel3.setBounds(0, 10, 280, 70);

        getContentPane().add(panelGradient4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 290, 87));

        panelGradient6.setBackground(new java.awt.Color(40, 184, 213));
        panelGradient6.setToolTipText("");
        panelGradient6.setColorGradient(new java.awt.Color(2, 3, 68));
        panelGradient6.setRadius(30);
        panelGradient6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGradient6MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/costumer.png"))); // NOI18N
        jLabel5.setText(" Customers Info");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        panelGradient6.add(jLabel5);
        jLabel5.setBounds(10, 10, 270, 70);

        getContentPane().add(panelGradient6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 290, 88));

        panelGradient9.setBackground(new java.awt.Color(40, 184, 213));
        panelGradient9.setToolTipText("");
        panelGradient9.setColorGradient(new java.awt.Color(2, 3, 68));
        panelGradient9.setRadius(30);
        panelGradient9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGradient9MousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/teamwork.png"))); // NOI18N
        jLabel8.setText("  Employee info");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        panelGradient9.add(jLabel8);
        jLabel8.setBounds(10, 0, 270, 90);

        getContentPane().add(panelGradient9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 290, 87));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("The Bold Font", 2, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/profile.png"))); // NOI18N
        jLabel6.setText("Manager Menu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 550, 150));

        jLabel9.setFont(new java.awt.Font("The Bold Font", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Manager Menu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 520, 120));

        panelGradient1.setBackground(new java.awt.Color(255, 102, 51));
        panelGradient1.setColorGradient(new java.awt.Color(255, 255, 102));
        panelGradient1.setRadius(35);
        panelGradient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGradient1MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("The Bold Font", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logout_1.png"))); // NOI18N
        jLabel1.setText("Log Out");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        panelGradient1.add(jLabel1);
        jLabel1.setBounds(10, 10, 230, 70);

        getContentPane().add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 250, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/abstract-blur-supermarket.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -100, 930, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelGradient4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient4MouseClicked
    this.setVisible(false);
        manager_products_frame y =new manager_products_frame();
        y.setVisible(true);

    }//GEN-LAST:event_panelGradient4MouseClicked

    private void panelGradient3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient3MousePressed
        this.setVisible(false);
        try {
            getBills billsframe=new getBills();
            billsframe.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(manager_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panelGradient3MousePressed

    private void panelGradient9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient9MousePressed
     this.setVisible(false);
        emplyeeInfo_frame employeeFrame=new emplyeeInfo_frame();
        employeeFrame.setVisible(true);             
    }//GEN-LAST:event_panelGradient9MousePressed

    private void panelGradient1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient1MousePressed
          this.setVisible(false);
        login x= new login();
        x.setVisible(true);

    }//GEN-LAST:event_panelGradient1MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            this.setVisible(false);
            getBills g1=new getBills();
            g1.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(manager_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void panelGradient6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient6MouseClicked
    
    }//GEN-LAST:event_panelGradient6MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(Color.CYAN);
       

    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
 jLabel8.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
       
                  jLabel3.setForeground(Color.CYAN);
     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setForeground(Color.white);        // TODO add your handling code here:
 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
                       jLabel5.setForeground(Color.CYAN);
   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
                            jLabel5.setForeground(Color.white);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
         jLabel1.setForeground(Color.CYAN);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
       jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
       jLabel7.setForeground(Color.CYAN);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(Color.white);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
this.setVisible(false);
        emplyeeInfo_frame employeeFrame=new emplyeeInfo_frame();
        employeeFrame.setVisible(true);                     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
   this.setVisible(false);
        manager_products_frame y =new manager_products_frame();
        y.setVisible(true);        
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    this.setVisible(false);
        ViewCustomersFrame view=new ViewCustomersFrame();
        view.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
  this.setVisible(false);
        login x= new login();
        x.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        try {
            
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(manager_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(manager_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(manager_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(manager_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            /* Create and display the form */
            
            //CHANGE THEME !!!
            UIManager.setLookAndFeel(new FlatDarkLaf());
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new manager_frame().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(manager_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private manager.PanelGradient panelGradient1;
    private manager.PanelGradient panelGradient3;
    private manager.PanelGradient panelGradient4;
    private manager.PanelGradient panelGradient5;
    private manager.PanelGradient panelGradient6;
    private manager.PanelGradient panelGradient9;
    // End of variables declaration//GEN-END:variables
}
