/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package manager;

import cashier.*;
import com.formdev.flatlaf.FlatDarkLaf;
import db_connection.db_connection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;
import manager.ViewEmployeesInternalFrame;
public class NewEmpInternalFrame extends javax.swing.JInternalFrame {

     Connection con;
     db_connection c= new db_connection();
    public NewEmpInternalFrame() {
        
         initComponents();
        
        con= c.connect();
      
         try {
           
            
            //Theme initialize
           
            UIManager.setLookAndFeel(new FlatDarkLaf());
            //view of internal frame modifications
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
            ui.setNorthPane(null);
            //disable Resize for internalJframe
            this.setResizable(false);
            
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ViewCustomerInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        employeeNameField = new javax.swing.JTextField();
        employeePhoneField = new javax.swing.JTextField();
        employeeAddressField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        employeeRoleComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        employeePasswordField = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelGradient2 = new cashier.PanelGradient();
        jLabel2 = new javax.swing.JLabel();
        panelGradient1 = new cashier.PanelGradient();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        employeeSallaryField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(80, 36));
        setNormalBounds(new java.awt.Rectangle(0, 0, 56, 0));
        setPreferredSize(new java.awt.Dimension(962, 706));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("The Bold Font", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 130, 50));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 30));

        employeeNameField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        employeeNameField.setForeground(new java.awt.Color(51, 255, 51));
        employeeNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(employeeNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 240, -1));

        employeePhoneField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        employeePhoneField.setForeground(new java.awt.Color(51, 255, 51));
        employeePhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeePhoneFieldActionPerformed(evt);
            }
        });
        jPanel1.add(employeePhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 240, -1));

        employeeAddressField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        employeeAddressField.setForeground(new java.awt.Color(51, 255, 51));
        employeeAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeAddressFieldActionPerformed(evt);
            }
        });
        jPanel1.add(employeeAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 240, -1));

        genderComboBox.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 240, -1));

        employeeRoleComboBox.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        employeeRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Stock Manager", "Cashier" }));
        employeeRoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeRoleComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(employeeRoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 240, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Salary");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Phone");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        employeePasswordField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel1.add(employeePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 240, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 110, 30));

        jLabel3.setFont(new java.awt.Font("The Bold Font", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SWIFT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 50));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        jLabel5.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jLabel5.setText("ADD EMPLOYEE...");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 30));

        jLabel6.setFont(new java.awt.Font("VIP Cartoon", 0, 24)); // NOI18N
        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jLabel6.setText("----------");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        panelGradient2.setBackground(new java.awt.Color(0, 159, 253));
        panelGradient2.setColorGradient(new java.awt.Color(42, 42, 114));
        panelGradient2.setRadius(40);
        panelGradient2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGradient2MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gilroy ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/back.png"))); // NOI18N
        jLabel2.setText("Back");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        panelGradient2.add(jLabel2);
        jLabel2.setBounds(10, 0, 140, 50);

        jPanel1.add(panelGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 160, 50));

        panelGradient1.setBackground(new java.awt.Color(0, 159, 253));
        panelGradient1.setColorGradient(new java.awt.Color(42, 42, 114));
        panelGradient1.setRadius(40);
        panelGradient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGradient1MousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Gilroy ExtraBold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADD Employee");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        panelGradient1.add(jLabel7);
        jLabel7.setBounds(20, -10, 180, 70);

        jPanel1.add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 220, 50));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Role");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 110, 30));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 110, 30));

        employeeSallaryField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPanel1.add(employeeSallaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 240, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/addemployee36686.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 300, 320));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/223.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1000, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameFieldActionPerformed

    }//GEN-LAST:event_employeeNameFieldActionPerformed

    private void employeePhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePhoneFieldActionPerformed

    }//GEN-LAST:event_employeePhoneFieldActionPerformed

    private void employeeAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeAddressFieldActionPerformed

    }//GEN-LAST:event_employeeAddressFieldActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed

    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void employeeRoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRoleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeRoleComboBoxActionPerformed

    private void panelGradient2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient2MousePressed
      ManagerPhase.jDesktopPane1.removeAll();
      ManagerPhase.jDesktopPane1.updateUI();
      ViewEmployeesInternalFrame view=new ViewEmployeesInternalFrame();
      ManagerPhase.jDesktopPane1.add(view).setVisible(true);
      
    }//GEN-LAST:event_panelGradient2MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        String employeeAddress = employeeAddressField.getText();
        if(employeeNameField.getText().isEmpty()||employeePhoneField.getText().isEmpty()||employeeAddressField.getText().isEmpty()||
            employeePasswordField.getPassword().length == 0||employeeSallaryField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter all the fields");
        }
        else if(employeePhoneField.getText().length() != 11 || !employeePhoneField.getText().startsWith("01")
            || employeePhoneField.getText().contains("[a-zA-Z]+"))
        {
            JOptionPane.showMessageDialog(this, "Enter valid phone number");
        }
        else
        {
            String EmployeeNameField = employeeNameField.getText(),
            employeePhone = employeePhoneField.getText(),
            //employeeAddress = employeeAddressField.getText(),
            employeeGender = genderComboBox.getSelectedItem().toString(),
            EmployeePassword = new String (employeePasswordField.getPassword()),
            employeeSallary = employeeSallaryField.getText(),
            EmployeeRole = employeeRoleComboBox.getSelectedItem().toString();

            PreparedStatement stmt;
            try {

                stmt = con.prepareStatement("Select *"
                    + "from employee inner join emp_phone "
                    + "on employee.employee_id = emp_phone.id inner join emp_address "
                    + "on employee.employee_id = emp_address.id where phone = ?");
                stmt.setString(1, employeePhone);

                ResultSet resultSet= stmt.executeQuery();

                if(resultSet.next() == true)
                {
                    JOptionPane.showMessageDialog(this, "User already exist the phone number is saved in the database");
                }
                else
                {
                    stmt = con.prepareStatement("""
                        DECLARE @ids TABLE (id INT);

                        INSERT INTO employee (name, gender, role, password, sallary)
                        OUTPUT inserted.employee_id INTO @ids
                        VALUES (?,?,?,?,?);

                        DECLARE @emp_id INT = (SELECT TOP 1 id FROM @ids);

                        INSERT INTO emp_phone (id, phone)
                        OUTPUT inserted.id INTO @ids
                        VALUES (@emp_id,?);

                        DECLARE @phone_id INT = (SELECT TOP 1 id FROM @ids);

                        INSERT INTO emp_address (id, address)
                        VALUES (@emp_id,?);""");
                        stmt.setString(1, EmployeeNameField);
                        stmt.setString(2, employeeGender);
                        stmt.setString(3, EmployeeRole);
                        stmt.setString(4, EmployeePassword);
                        stmt.setFloat(5, Float.parseFloat(employeeSallary));
                        stmt.setString(6, employeePhone);
                        stmt.setString(7, employeeAddress);

                        stmt.executeQuery();

                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "User added successfully");

                    employeeNameField.setText("");
                    employeePhoneField.setText("");
                    employeeAddressField.setText("");
                    genderComboBox.setSelectedIndex(0);
                    employeePasswordField.setText("");
                    employeeSallaryField.setText("");
                    employeeRoleComboBox.setSelectedIndex(0);

                    //  ViewEmloyeesInternalFrame empObject = new ViewEmloyeesInternalFrame();
                    //   empObject.setVisible(true);
                }

            }

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(Color.GREEN);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed

    }//GEN-LAST:event_jLabel7MousePressed

    private void panelGradient1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient1MousePressed

    }//GEN-LAST:event_panelGradient1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
       ManagerPhase.jDesktopPane1.removeAll();
      ManagerPhase.jDesktopPane1.updateUI();
      ViewEmployeesInternalFrame view=new ViewEmployeesInternalFrame();
      ManagerPhase.jDesktopPane1.add(view).setVisible(true);
      
    }//GEN-LAST:event_jLabel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employeeAddressField;
    private javax.swing.JTextField employeeNameField;
    private javax.swing.JPasswordField employeePasswordField;
    private javax.swing.JTextField employeePhoneField;
    private javax.swing.JComboBox<String> employeeRoleComboBox;
    private javax.swing.JTextField employeeSallaryField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private cashier.PanelGradient panelGradient1;
    private cashier.PanelGradient panelGradient2;
    // End of variables declaration//GEN-END:variables
}
