/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Bill;

import com.formdev.flatlaf.FlatDarkLaf;
import db_connection.db_connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import manager.ManagerPhase;

import net.proteanit.sql.DbUtils;
/**
 *
 * @author medo4
 */
public class DisplayAllBillsInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DisplayAllBillsInternalFrame
     */
     public static String orderID;
  
      Connection con;
    db_connection c= new db_connection();
    public void fetchAllBills(){
      try{
          con= c.connect();
            String selectedColoumns = "order_id,first_name,last_name,cashier_id,date";
             
                PreparedStatement stmt = con.prepareStatement(
                    String.format("SELECT %s FROM orders join customer on customer.customer_id = orders.customer_id;",selectedColoumns));

                ResultSet resultSet = stmt.executeQuery();

                BillsInfo.setModel(DbUtils.resultSetToTableModel(resultSet));
        }
        catch(SQLException ex)
        {
            
        }
}
     public static String returnID()
   {
       return orderID;
   }
    public DisplayAllBillsInternalFrame() {
        initComponents();
        
         try {
             //Theme initialize

             UIManager.setLookAndFeel(new FlatDarkLaf());
         } catch (UnsupportedLookAndFeelException ex) {
             Logger.getLogger(DisplayAllBillsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
            //view of internal frame modifications
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
            ui.setNorthPane(null);
            //disable Resize for internalJframe
            this.setResizable(false);
            
            fetchAllBills();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayAllBills = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillsInfo = new javax.swing.JTable();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchType = new javax.swing.JComboBox<>();
        showBillButton = new javax.swing.JButton();
        searchLabel1 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        message_Label = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayAllBills.setkEndColor(new java.awt.Color(0, 153, 255));
        displayAllBills.setkStartColor(new java.awt.Color(0, 153, 204));
        displayAllBills.setPreferredSize(new java.awt.Dimension(812, 584));
        displayAllBills.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BillsInfo.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        BillsInfo.setForeground(new java.awt.Color(255, 255, 255));
        BillsInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "order_id", "customer id", "cashier_id", "date"
            }
        ));
        BillsInfo.setSelectionBackground(new java.awt.Color(26, 226, 141));
        BillsInfo.setSelectionForeground(new java.awt.Color(255, 255, 255));
        BillsInfo.setShowVerticalLines(true);
        BillsInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillsInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BillsInfo);

        displayAllBills.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 96, 880, 480));

        searchLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 250, 244));
        searchLabel.setText("BILLS INFORMATION");
        displayAllBills.add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 50));

        searchField.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });
        displayAllBills.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 229, 30));

        searchType.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        searchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order ID", "Customer ID", "Cashier ID" }));
        displayAllBills.add(searchType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 150, 30));

        showBillButton.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        showBillButton.setForeground(new java.awt.Color(51, 255, 51));
        showBillButton.setText("Show Bill Info");
        showBillButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBillButtonActionPerformed(evt);
            }
        });
        displayAllBills.add(showBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 200, 50));

        searchLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        searchLabel1.setForeground(new java.awt.Color(255, 250, 244));
        searchLabel1.setText("Search");
        displayAllBills.add(searchLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 130, 30));

        lab.setBackground(new java.awt.Color(51, 51, 51));
        lab.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lab.setForeground(new java.awt.Color(255, 255, 255));
        lab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/billicon.png"))); // NOI18N
        lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labMouseExited(evt);
            }
        });
        displayAllBills.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 80, 70));

        message_Label.setFont(new java.awt.Font("Teen-Poem", 1, 18)); // NOI18N
        message_Label.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        displayAllBills.add(message_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 490, 20));

        getContentPane().add(displayAllBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BillsInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsInfoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BillsInfoMouseClicked
   
    private void showBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBillButtonActionPerformed
       
        int row =BillsInfo.getSelectedRow();
        if (row<0)
        {JOptionPane.showMessageDialog(null, "Please Select Order");}
        else
        {
            orderID=BillsInfo.getValueAt(row, 0).toString();
            
             showBillInternalFrame view=new showBillInternalFrame();
            ManagerPhase.jDesktopPane1.removeAll();
            ManagerPhase.jDesktopPane1.updateUI();
            ManagerPhase.jDesktopPane1.add(view).setVisible(true);
           

            String BillID =    BillsInfo.getValueAt(row, 1).toString();
            String FirstNameCustomer =    BillsInfo.getValueAt(row, 1).toString();
            String SecondNameCustomer =    BillsInfo.getValueAt(row, 2).toString();
            String orderID =    BillsInfo.getValueAt(row, 0).toString();

            showBillInternalFrame.retCustomerName.setText(FirstNameCustomer+" "+SecondNameCustomer);
            String selectedColoumns = "products.name,order_items.quantity,products.price,products.discount";
            PreparedStatement stmt;
            try {
                stmt = con.prepareStatement(
                    String.format("SELECT %s FROM order_items join products on order_items.product_id = products.product_id where order_id = ?;",selectedColoumns));
                stmt.setString(1, orderID);
                ResultSet resultSet = stmt.executeQuery();

                showBillInternalFrame.info_bills.setModel(DbUtils.resultSetToTableModel(resultSet));
            } catch (SQLException ex) {
                Logger.getLogger(DisplayAllBillsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
            

        }

    }//GEN-LAST:event_showBillButtonActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        if("".equals(searchField.getText().trim()))
        {
               fetchAllBills();
        
           
        }
        else
        {

            try {
                String s;
                switch (searchType.getSelectedIndex()) {
                    case 1 ->  s = "orders.customer_id";
                    case 2 ->  s = "cashier_id";
                    default -> s = "order_id";
                }
                String selectedColoumns = "order_id,first_name,last_name,cashier_id";
                PreparedStatement stmt = con.prepareStatement(
                    String.format("SELECT %s FROM orders join customer on customer.customer_id = orders.customer_id where %s = ?;",selectedColoumns,s));

                stmt.setString(1, searchField.getText().trim());

                ResultSet resultSet = stmt.executeQuery();

                BillsInfo.setModel(DbUtils.resultSetToTableModel(resultSet));

            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_searchFieldKeyReleased

    private void labMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_labMouseEntered

    private void labMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labMouseExited

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        
    }//GEN-LAST:event_searchFieldKeyTyped

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        char c= evt.getKeyChar();
        if(Character.isLetter(c)){
            searchField.setEditable(false);
            message_Label.setText("Please Enter numbers only");
        }
        else{
            searchField.setEditable(true);
            message_Label.setText("");

        }
        
        
         
    }//GEN-LAST:event_searchFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillsInfo;
    private keeptoo.KGradientPanel displayAllBills;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel message_Label;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel searchLabel1;
    private javax.swing.JComboBox<String> searchType;
    private javax.swing.JButton showBillButton;
    // End of variables declaration//GEN-END:variables
}
