/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Bill;




import com.formdev.flatlaf.FlatDarkLaf;
import db_connection.db_connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import manager.ManagerPhase;
import manager.ViewEmployeesInternalFrame;

import net.proteanit.sql.DbUtils;

/**
 *
 * @author medo4
 */
public class showBillInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form showBillInternalFrame
     */
      Connection con;
    db_connection c= new db_connection();
    
    
    
    
    public showBillInternalFrame() {
        
        initComponents();
        
          try {
              //Theme initialize

              UIManager.setLookAndFeel(new FlatDarkLaf());
          } catch (UnsupportedLookAndFeelException ex) {
              Logger.getLogger(showBillInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
            //view of internal frame modifications
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
            ui.setNorthPane(null);
            //disable Resize for internalJframe
            this.setResizable(false);
        idLabel.setText("ID ="+DisplayAllBillsInternalFrame.returnID());
        
        
        
        con= c.connect();
        
        String selectedColoumns = "products.name,order_items.quantity,products.price,products.discount";
            PreparedStatement stmt;
            try {
                
                stmt = con.prepareStatement(
                    String.format("SELECT %s FROM order_items join products on order_items.product_id = products.product_id where order_id = ?;",selectedColoumns));
                stmt.setString(1, DisplayAllBillsInternalFrame.returnID());
                ResultSet resultSet = stmt.executeQuery();

                showBillInternalFrame.info_bills.setModel(DbUtils.resultSetToTableModel(resultSet));
            } catch (SQLException ex) {
                Logger.getLogger(showBillInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                float totalprice=0;
                int rownumber=info_bills.getRowCount();
                for(int i=0;i<rownumber;i++)
                {
                    
                    int quantity;
                    float price,discount,priceitem;
                     quantity=Integer.parseInt( info_bills.getValueAt(i, 1).toString());
                     price=Float.parseFloat(info_bills.getValueAt(i, 2).toString());
                     discount= Float.parseFloat( info_bills.getValueAt(i, 3).toString());
                    priceitem=(price*quantity)-(price*quantity*discount);
                    totalprice+=priceitem;
                   
                }
               total.setText(Float.toString(totalprice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayAllBills = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        info_bills = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        retCustomerName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        customerName1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        labbbel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayAllBills.setkEndColor(new java.awt.Color(0, 153, 255));
        displayAllBills.setkStartColor(new java.awt.Color(0, 153, 204));
        displayAllBills.setPreferredSize(new java.awt.Dimension(812, 584));
        displayAllBills.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gilroy ExtraBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/back.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        displayAllBills.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 60, 40));

        info_bills.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        info_bills.setForeground(new java.awt.Color(255, 255, 255));
        info_bills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee_id", "name", "role", "phone", "address", "gender", "salary"
            }
        ));
        info_bills.setShowVerticalLines(true);
        info_bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info_billsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(info_bills);

        displayAllBills.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 75, 870, 490));

        total.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        total.setForeground(new java.awt.Color(51, 255, 51));
        total.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        total.setText("Total:");
        displayAllBills.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 140, 60));

        retCustomerName.setFont(new java.awt.Font("Gilroy ExtraBold", 1, 36)); // NOI18N
        retCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        retCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        retCustomerName.setText("Customer name");
        displayAllBills.add(retCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 60));

        jButton1.setFont(new java.awt.Font("Gilroy Light", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back  ");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        displayAllBills.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 160, 40));

        customerName1.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        customerName1.setForeground(new java.awt.Color(255, 255, 255));
        customerName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerName1.setText("Customer name :");
        displayAllBills.add(customerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        idLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idLabel.setText("Customer name :");
        displayAllBills.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 60));

        labbbel.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        labbbel.setForeground(new java.awt.Color(255, 255, 255));
        labbbel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labbbel.setText("Total :");
        displayAllBills.add(labbbel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 70, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/money-bag (1).png"))); // NOI18N
        displayAllBills.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, -1, 50));

        getContentPane().add(displayAllBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void info_billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_billsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_info_billsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ManagerPhase.jDesktopPane1.removeAll();
       ManagerPhase.jDesktopPane1.updateUI();
       DisplayAllBillsInternalFrame view=new DisplayAllBillsInternalFrame();
       ManagerPhase.jDesktopPane1.add(view).setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
     

    }//GEN-LAST:event_jLabel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerName1;
    private keeptoo.KGradientPanel displayAllBills;
    private javax.swing.JLabel idLabel;
    public static javax.swing.JTable info_bills;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labbbel;
    public static javax.swing.JLabel retCustomerName;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
