/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cashier;

/**
 *
 * @author medo4
 */



import com.formdev.flatlaf.FlatDarkLaf;
import db_connection.db_connection;
import java.awt.Color;
import java.awt.Label;
import java.awt.Panel;
import java.util.ArrayList;
import javax.swing.JPanel;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import net.proteanit.sql.DbUtils;
import billing_system_project.login;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import manager.ViewEmployeesInternalFrame;

public class CustomerListInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CustomerListInternalFrame
     */
    public CustomerListInternalFrame() {
        
         try {
             UIManager.setLookAndFeel(new FlatDarkLaf());
         } catch (UnsupportedLookAndFeelException ex) {
             Logger.getLogger(ViewEmployeesInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
            //view of internal frame modifications
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
            ui.setNorthPane(null);
            //disable Resize for internalJframe
            this.setResizable(false);
            
            
        initComponents();
         try {
           
            UIManager.setLookAndFeel(new FlatDarkLaf());
            showdata();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CustomerListInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
       public static void showdata()
    {
         Connection conn;
         PreparedStatement ps;
         ResultSet res;
         
         
         ArrayList <Customerinfo> data=new ArrayList<>();
         DefaultTableModel t1=(DefaultTableModel) CustomersTable.getModel();
        try{          
//Connection to database
            String URL = "jdbc:sqlserver://localhost:1433;databaseName=Billing_system_db;integratedSecurity=true;encrypt=false";
            conn = DriverManager.getConnection(URL);
           String Query="SELECT customer_id as ID,first_name+' '+last_name as Name,phone,address,membership FROM customer c JOIN cus_phone cp ON c.customer_id=cp.id JOIN cus_address ca ON cp.id=ca.id;";
           ps=conn.prepareStatement(Query);
           res=ps.executeQuery();
 //put data into arraylist and from this to array to table    

          Object [] eachrow=new Object[6];
          while(res.next())
          {
              data.add(new Customerinfo (res.getInt("ID"),res.getString("Name"),res.getString("phone")
              ,res.getString("address"),res.getString("membership")));
              
          }
         
  //from Arraylist to obj array then to table 
          for (int i=0;i<data.size();i++)
          {
              eachrow[0]=data.get(i).getCust_id();
              eachrow[1]=data.get(i).getname();
              eachrow[2]=data.get(i).getPhone();
              eachrow[3]=data.get(i).getAddress();
              eachrow[4]=data.get(i).getMembership();
             
              t1.addRow(eachrow);
          }
           
        }
        catch (SQLException ex) {
            Logger.getLogger(CustomerListInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
      
        
    }
    public void SetColor (Label obj)
    {
        obj.setForeground(Color.red);
    }
     public void ResetColor (Label obj)
    {
        
        obj.setForeground(Color.WHITE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();
        keytext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sort = new javax.swing.JComboBox<>();
        panelGradient2 = new cashier.PanelGradient();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1076, 588));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 153));
        jScrollPane1.setBorder(null);

        CustomersTable.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Address", "Membership"
            }
        ){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        CustomersTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        CustomersTable.setColumnSelectionAllowed(true);
        CustomersTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CustomersTable.setShowVerticalLines(true);
        CustomersTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CustomersTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(CustomersTable);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 900, 430));

        keytext.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        keytext.setToolTipText("General Search");
        keytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keytextActionPerformed(evt);
            }
        });
        keytext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keytextKeyReleased(evt);
            }
        });
        kGradientPanel1.add(keytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 266, 32));

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Order by");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 110, 30));
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 440, 28, 27));

        sort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID ↑", "ID ↓", "Name ↑", "Name ↓", "Membership ↑", "Membership ↓" }));
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });
        kGradientPanel1.add(sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 160, -1));

        panelGradient2.setBackground(new java.awt.Color(0, 255, 102));
        panelGradient2.setForeground(new java.awt.Color(255, 255, 255));
        panelGradient2.setColorGradient(new java.awt.Color(0, 255, 51));
        panelGradient2.setRadius(30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/billicon.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        panelGradient2.add(jLabel7);
        jLabel7.setBounds(140, 0, 70, 60);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Make Bill");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        panelGradient2.add(jLabel4);
        jLabel4.setBounds(10, 0, 150, 70);

        kGradientPanel1.add(panelGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 210, 70));

        jLabel6.setBackground(new java.awt.Color(255, 0, 102));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("General Search");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 180, 32));

        lab1.setBackground(new java.awt.Color(255, 255, 255));
        lab1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("CUSTOMER INFORMATION");
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab1MouseExited(evt);
            }
        });
        kGradientPanel1.add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 45));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/costumer.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 80));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/search icon.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 70, 70));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomersTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CustomersTableComponentShown

    }//GEN-LAST:event_CustomersTableComponentShown

    private void keytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keytextActionPerformed

    private void keytextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keytextKeyReleased
        DefaultTableModel table=(DefaultTableModel) CustomersTable.getModel();

        String searchkey=keytext.getText();

        String pattern = "(?i)^" + searchkey;
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter <>(table);
        CustomersTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(pattern));
    }//GEN-LAST:event_keytextKeyReleased

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        String sort_by;
        String query;
        sort_by = (String) sort.getSelectedItem();
        switch(sort_by){
            case "ID ↑" -> {query = "select customer_id as ID, first_name+' '+last_name as Name,  cus_phone.phone as Phone,cus_address.address as Address , membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by customer_id";}
            case "ID ↓" -> {query = " select customer_id as ID, first_name+' '+last_name as Name, cus_phone.phone as Phone,cus_address.address as Address, membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by customer_id DESC;";}
            case "Name ↑" -> {query = "select customer_id as ID, first_name+' '+last_name as Name,cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by first_name,last_name";}
            case "Name ↓" -> {query = " select customer_id as ID, first_name+' '+last_name as Name, cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by first_name DESC,last_name DESC";}
            case "Membership ↑" -> {query = "select customer_id as ID, first_name+' '+last_name as Name, cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by membership";}
            default -> {query = "select customer_id as ID, first_name+' '+last_name as Name,  cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by customer_id DESC";}
        }
        try{
            Connection conn= db_connection.connect();
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            if(rs != null) {
                CustomersTable.setModel(DbUtils.resultSetToTableModel(rs));
                while(rs.next()){
                    System.out.println(rs.getInt(1));
                }

            }else{System.out.println("Hello");}
        }catch (SQLException ee){
            System.out.println(ee.getMessage());
        }catch(Exception ee){
            System.out.println(ee.getMessage());
        }
    }//GEN-LAST:event_sortActionPerformed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int row = CustomersTable.getSelectedRow();
        if(row > 0)
        {
            id = Integer.parseInt(CustomersTable.getValueAt(row, 0).toString());
            String memberShip = CustomersTable.getValueAt(row,4).toString();
            discount = 0;

            if(null != memberShip)
            switch (memberShip) {
                case "Gold":
                discount = (float) 0.25;
                break;
                case "Silver":
                discount = (float) 0.10;
                break;
                case "Bronze":
                discount = (float) 0.05;
                break;
                case "none":
                discount = (float) 0.00;
                break;
                case "Platinum":
                discount = (float) 0.3;
                break;
                default:
                break;
            }
            System.out.print(discount);
      
        CashierPhase.jDesktopPane1.removeAll();
        CashierPhase.jDesktopPane1.updateUI();
        OrderItemsInternalFrame order_obj=new OrderItemsInternalFrame();
        CashierPhase.jDesktopPane1.add(order_obj).setVisible(true);
       
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases Select Customer First");
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        Color a=new Color(51,0,204) ;
        jLabel4.setForeground(a);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_jLabel4MouseExited

    static float discount;
    public static float getDiscount()
    {
        return discount;
    }
      
    static int id;
    public static int getID()
    {
        return id;
    }
    private void lab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lab1MouseEntered

    private void lab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lab1MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable CustomersTable;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField keytext;
    private javax.swing.JLabel lab1;
    private cashier.PanelGradient panelGradient2;
    private javax.swing.JComboBox<String> sort;
    // End of variables declaration//GEN-END:variables
}
