/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cashier;



import Bill.order_items;
import com.formdev.flatlaf.FlatDarkLaf;
import db_connection.db_connection;
import java.awt.Color;
import java.awt.Label;
import java.awt.Panel;
import java.util.ArrayList;
import javax.swing.JPanel;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import manager.manager_frame;
import net.proteanit.sql.DbUtils;
import billing_system_project.login;
import cashier.newCustomerFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author medo4
 */
public class ViewCustomersFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewCustomersFrame
     */
    public ViewCustomersFrame() {
        try {
            initComponents();
            UIManager.setLookAndFeel(new FlatDarkLaf());
            showdata();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ViewCustomersFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }
    public void showdata()
    {
         Connection conn;
         PreparedStatement ps;
         ResultSet res;
         
         
         ArrayList <Customerinfo> data=new ArrayList<>();
         DefaultTableModel t1=(DefaultTableModel) CustomersTable.getModel();
        try{          
//Connection to database
            String URL = "jdbc:sqlserver://localhost:1433;databaseName=Billing_system_db;integratedSecurity=true;encrypt=false";
            conn = DriverManager.getConnection(URL);
           String Query="SELECT customer_id as ID,first_name+' '+last_name as Name,phone,address,membership FROM customer c JOIN cus_phone cp ON c.customer_id=cp.id JOIN cus_address ca ON cp.id=ca.id;";
           ps=conn.prepareStatement(Query);
           res=ps.executeQuery();
 //put data into arraylist and from this to array to table    

          Object [] eachrow=new Object[6];
          while(res.next())
          {
              data.add(new Customerinfo (res.getInt("ID"),res.getString("Name"),res.getString("phone")
              ,res.getString("address"),res.getString("membership")));
              
          }
         
  //from Arraylist to obj array then to table 
          for (int i=0;i<data.size();i++)
          {
              eachrow[0]=data.get(i).getCust_id();
              eachrow[1]=data.get(i).getname();
              eachrow[2]=data.get(i).getPhone();
              eachrow[3]=data.get(i).getAddress();
              eachrow[4]=data.get(i).getMembership();
             
              t1.addRow(eachrow);
          }
           
        }
        catch (SQLException ex) {
            Logger.getLogger(ViewCustomersFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
      
        
    }
    public void SetColor (Label obj)
    {
        obj.setForeground(Color.red);
    }
     public void ResetColor (Label obj)
    {
        
        obj.setForeground(Color.WHITE);
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomersTable = new javax.swing.JTable();
        keytext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sort = new javax.swing.JComboBox<>();
        panelGradient2 = new cashier.PanelGradient();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelGradient1 = new cashier.PanelGradient();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        labelbutton = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customers Details");
        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 255, 204));
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1076, 588));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 153));
        jScrollPane1.setBorder(null);

        CustomersTable.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        CustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Address", "Membership"
            }
        ){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        CustomersTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        CustomersTable.setColumnSelectionAllowed(true);
        CustomersTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CustomersTable.setShowVerticalLines(true);
        CustomersTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CustomersTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(CustomersTable);
        CustomersTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 850, 380));

        keytext.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        keytext.setToolTipText("General Search");
        keytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keytextActionPerformed(evt);
            }
        });
        keytext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keytextKeyReleased(evt);
            }
        });
        kGradientPanel1.add(keytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 266, 32));

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Order by");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 110, 30));
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 440, 28, 27));

        sort.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID ↑", "ID ↓", "Name ↑", "Name ↓", "Membership ↑", "Membership ↓" }));
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });
        kGradientPanel1.add(sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 160, -1));

        panelGradient2.setBackground(new java.awt.Color(0, 255, 102));
        panelGradient2.setForeground(new java.awt.Color(255, 255, 255));
        panelGradient2.setColorGradient(new java.awt.Color(0, 255, 51));
        panelGradient2.setRadius(30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/billicon.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        panelGradient2.add(jLabel7);
        jLabel7.setBounds(140, 0, 70, 60);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Make Bill");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        panelGradient2.add(jLabel4);
        jLabel4.setBounds(0, 0, 150, 60);

        kGradientPanel1.add(panelGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 210, 60));

        jLabel6.setBackground(new java.awt.Color(255, 0, 102));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("General Search");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 180, 32));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGradient1.setBackground(new java.awt.Color(0, 255, 102));
        panelGradient1.setForeground(new java.awt.Color(255, 255, 255));
        panelGradient1.setColorGradient(new java.awt.Color(0, 255, 51));
        panelGradient1.setRadius(30);
        panelGradient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelGradient1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add New Customer");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        panelGradient1.add(jLabel5);
        jLabel5.setBounds(10, 0, 160, 50);

        jPanel1.add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 50));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cashier ID");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 30));

        lab.setBackground(new java.awt.Color(255, 255, 255));
        lab.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lab.setForeground(new java.awt.Color(0, 204, 255));
        lab.setText("MENU");
        lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labMouseExited(evt);
            }
        });
        jPanel1.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 50));

        lab2.setBackground(new java.awt.Color(255, 255, 255));
        lab2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lab2.setForeground(new java.awt.Color(255, 255, 255));
        lab2.setText("CASHIER");
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab2MouseExited(evt);
            }
        });
        jPanel1.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 70));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cashier Name");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/clerk.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 90));

        kGradientPanel2.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 153, 153));
        kGradientPanel2.setkGradientFocus(200);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 102, 102));
        kGradientPanel2.setMaximumSize(new java.awt.Dimension(800, 800));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelbutton.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        labelbutton.setForeground(new java.awt.Color(255, 255, 255));
        labelbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logouticon.png"))); // NOI18N
        labelbutton.setText("LOG OUT");
        labelbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelbuttonMouseClicked(evt);
            }
        });
        kGradientPanel2.add(labelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 180, 60));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 210, 640));

        lab1.setBackground(new java.awt.Color(255, 255, 255));
        lab1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("CUSTOMER INFORMATION");
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab1MouseExited(evt);
            }
        });
        kGradientPanel1.add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 45));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/costumer.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 160, 80));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/search icon.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keytextKeyReleased(java.awt.event.KeyEvent evt) {                                    
//GEN-FIRST:event_keytextKeyReleased
        DefaultTableModel table=(DefaultTableModel) CustomersTable.getModel();

        String searchkey=keytext.getText();

    String pattern = "(?i)^" + searchkey;
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter <>(table);
        CustomersTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(pattern));
    }//GEN-LAST:event_keytextKeyReleased

    private void keytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keytextActionPerformed

    private void CustomersTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CustomersTableComponentShown

    }//GEN-LAST:event_CustomersTableComponentShown

    private void labelbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbuttonMouseClicked
login m1= new login();
this.setVisible(false);
m1.setVisible(true);
    }//GEN-LAST:event_labelbuttonMouseClicked

    private void labMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseEntered
         Color a=new Color(51,0,204) ;
        lab.setForeground(a);
// TODO add your handling code here:
    }//GEN-LAST:event_labMouseEntered

    private void labMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseExited
lab.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_labMouseExited

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
      String sort_by;
        String query;
        sort_by = (String) sort.getSelectedItem();
        switch(sort_by){
                case "ID ↑" -> {query = "select customer_id as ID, first_name+' '+last_name as Name,  cus_phone.phone as Phone,cus_address.address as Address , membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by customer_id";}
                case "ID ↓" -> {query = " select customer_id as ID, first_name+' '+last_name as Name, cus_phone.phone as Phone,cus_address.address as Address, membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by customer_id DESC;";}
                case "Name ↑" -> {query = "select customer_id as ID, first_name+' '+last_name as Name,cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by first_name,last_name";}
                case "Name ↓" -> {query = " select customer_id as ID, first_name+' '+last_name as Name, cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by first_name DESC,last_name DESC";}
                case "Membership ↑" -> {query = "select customer_id as ID, first_name+' '+last_name as Name, cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by membership";}
                default -> {query = "select customer_id as ID, first_name+' '+last_name as Name,  cus_phone.phone as Phone,cus_address.address as Address,membership as Membership from customer, cus_phone,cus_address where customer_id = cus_phone.id and customer_id = cus_address.id order by customer_id DESC";}
            }
        try{
            Connection conn= db_connection.connect();
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            if(rs != null) {
                CustomersTable.setModel(DbUtils.resultSetToTableModel(rs));
                while(rs.next()){
                    System.out.println(rs.getInt(1));
                }
                
            }else{System.out.println("Hello");}
        }catch (SQLException ee){
            System.out.println(ee.getMessage());
        }catch(Exception ee){
            System.out.println(ee.getMessage());
        }
    }//GEN-LAST:event_sortActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        Color a=new Color(51,0,204) ;
        jLabel4.setForeground(a);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.white);
    }//GEN-LAST:event_jLabel4MouseExited
static float discount;
    public static float getDiscount()
    {
        return discount;
    }
      
    static int id;
    public static int getID()
    {
        return id;
    }
 
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int row = CustomersTable.getSelectedRow();
        if(row > 0)
        {
            id = Integer.parseInt(CustomersTable.getValueAt(row, 0).toString());
            String memberShip = CustomersTable.getValueAt(row,4).toString();
            discount = 0;


            if(null != memberShip)
            switch (memberShip) {
                case "Gold":
                    discount = (float) 0.25;
                    break;
                case "Silver":
                    discount = (float) 0.10;
                    break;
                case "Bronze":
                    discount = (float) 0.05;
                    break;
                case "none":
                    discount = (float) 0.00;
                    break;
                case "Platinum":
                    discount = (float) 0.3;
                    break;
                default:
                    break;
            }
            System.out.print(discount);
            order_items ord = new order_items();
            ord.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Pleases Select Customer First");
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        newCustomerFrame newcustomer=new newCustomerFrame();
        newcustomer.setVisible(true);       
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void lab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lab1MouseEntered

    private void lab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lab1MouseExited

    private void lab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lab2MouseEntered

    private void lab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lab2MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void panelGradient1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient1MouseClicked
         newCustomerFrame newcustomer=new newCustomerFrame();
        newcustomer.setVisible(true);
    }//GEN-LAST:event_panelGradient1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            try {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                */
                UIManager.setLookAndFeel(new FlatDarkLaf());
                
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(ViewCustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(ViewCustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(ViewCustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(ViewCustomersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new ViewCustomersFrame().setVisible(true);
                    }
                });
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(ViewCustomersFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            //</editor-fold>
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ViewCustomersFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CustomersTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField keytext;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel labelbutton;
    private cashier.PanelGradient panelGradient1;
    private cashier.PanelGradient panelGradient2;
    private javax.swing.JComboBox<String> sort;
    // End of variables declaration//GEN-END:variables
}
