package Products;



import db_connection.db_connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import net.proteanit.sql.DbUtils;
/**
 *
 * @author medo4
 */
public class displayAllBills extends javax.swing.JInternalFrame {

    /**
     * Creates new form displayAllBills
     */
    
    Connection con;
    db_connection c= new db_connection();
    public displayAllBills() {
        initComponents();
          con= c.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayAllBills = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillsInfo = new javax.swing.JTable();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchType = new javax.swing.JComboBox<>();
        showBillButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        displayAllBills.setBackground(new java.awt.Color(51, 51, 51));

        BillsInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 173, 252)));
        BillsInfo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BillsInfo.setForeground(new java.awt.Color(255, 255, 255));
        BillsInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bills_id", "Customer id", "Cashier_id", "Date"
            }
        ));
        BillsInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillsInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BillsInfo);

        searchLabel.setForeground(new java.awt.Color(255, 250, 244));
        searchLabel.setText("Search:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order ID", "Customer ID", "Cashier ID" }));

        showBillButton.setText("Show Bill Info");
        showBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBillButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayAllBillsLayout = new javax.swing.GroupLayout(displayAllBills);
        displayAllBills.setLayout(displayAllBillsLayout);
        displayAllBillsLayout.setHorizontalGroup(
            displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayAllBillsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayAllBillsLayout.createSequentialGroup()
                        .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(searchButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(displayAllBillsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(displayAllBillsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(showBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        displayAllBillsLayout.setVerticalGroup(
            displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayAllBillsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(displayAllBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayAllBillsLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayAllBillsLayout.createSequentialGroup()
                        .addComponent(showBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayAllBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayAllBills, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BillsInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillsInfoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BillsInfoMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if("".equals(searchField.getText().trim()))
        {
            JOptionPane.showMessageDialog(this, "Enter a value");
        }
        else
        {

            try {
                String s;
                switch (searchType.getSelectedIndex()) {
                    case 1 ->  s = "customer_id";
                    case 2 ->  s = "cashier_id";
                    default -> s = "order_id";
                }
                String selectedColoumns = "order_id,first_name,last_name,cashier_id";
                PreparedStatement stmt = con.prepareStatement(
                    String.format("SELECT %s FROM orders join customer on customer.customer_id = orders.customer_id where order_id = ?;",selectedColoumns,s));

                stmt.setString(1, searchField.getText().trim());

                ResultSet resultSet = stmt.executeQuery();

                BillsInfo.setModel(DbUtils.resultSetToTableModel(resultSet));

            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    static String cusName, orderID;
    public static String getCusName()
    {
        return cusName;
    }
    
    public static String getOrderID()
    {
        return orderID;
    }
    private void showBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBillButtonActionPerformed
        // TODO add your handling code here:
        int row =        BillsInfo.getSelectedRow();
        if (row<0)
        {JOptionPane.showMessageDialog(null, "Please Select Order");}
        else
        {
            displayAllBills.setVisible(false);
            
            String FirstNameCustomer =    BillsInfo.getValueAt(row, 1).toString();
            String SecondNameCustomer =    BillsInfo.getValueAt(row, 2).toString();
            orderID =    BillsInfo.getValueAt(row, 0).toString();
            
            cusName = FirstNameCustomer+" "+SecondNameCustomer;
            
            getBills showBill;
            try {
                showBill = new getBills();
                showBill.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(displayAllBills.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
           

    }//GEN-LAST:event_showBillButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillsInfo;
    private javax.swing.JPanel displayAllBills;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JComboBox<String> searchType;
    private javax.swing.JButton showBillButton;
    // End of variables declaration//GEN-END:variables
}
