package Products;


import db_connection.db_connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import manager.manager_frame;
import net.proteanit.sql.DbUtils;
import Products.displayAllBills;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class getBills extends javax.swing.JFrame {

    /**
     * Creates new form getBills
     */
    Connection con;
            db_connection c= new db_connection();
    public getBills() throws SQLException {
        initComponents();
        con= c.connect();
        retCustomerName.setText(displayAllBills.getCusName());
        
        try{
            String selectedColoumns = "order_id,first_name,last_name,cashier_id";
                PreparedStatement stmt = con.prepareStatement(
       String.format("SELECT %s FROM orders join customer on customer.customer_id = orders.customer_id;",selectedColoumns));

                ResultSet resultSet = stmt.executeQuery();

                info_bills.setModel(DbUtils.resultSetToTableModel(resultSet));
        }
        catch(SQLException ex)
        {
            
        }
        
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showBill = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        info_bills = new javax.swing.JTable();
        customerName = new javax.swing.JLabel();
        retCustomerName = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showBill.setBackground(new java.awt.Color(51, 51, 51));

        info_bills.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 173, 252)));
        info_bills.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        info_bills.setForeground(new java.awt.Color(255, 255, 255));
        info_bills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee_id", "name", "role", "phone", "address", "gender", "sallary"
            }
        ));
        info_bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info_billsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(info_bills);

        customerName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        customerName.setForeground(new java.awt.Color(255, 255, 255));
        customerName.setText("Customer name:");

        retCustomerName.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        retCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        retCustomerName.setText("Customer name:");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showBillLayout = new javax.swing.GroupLayout(showBill);
        showBill.setLayout(showBillLayout);
        showBillLayout.setHorizontalGroup(
            showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showBillLayout.createSequentialGroup()
                        .addGroup(showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(showBillLayout.createSequentialGroup()
                                .addComponent(customerName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(retCustomerName)))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showBillLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back)
                        .addGap(93, 93, 93))))
        );
        showBillLayout.setVerticalGroup(
            showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(719, 719, 719))
        );

        getContentPane().add(showBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void info_billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_billsMouseClicked
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_info_billsMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        
        showBill.setVisible(false);       
        displayAllBills dispBill = new displayAllBills();
        dispBill.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new getBills().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(getBills.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel customerName;
    private javax.swing.JTable info_bills;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel retCustomerName;
    private javax.swing.JPanel showBill;
    // End of variables declaration//GEN-END:variables
}
