/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Products;


import billing_system_project.login;
import static billing_system_project.login.get_StockManager_id;
import static billing_system_project.login.get_cashier_id;
import cashier.CashierPhase;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.ui.FlatListCellBorder.Default;
import db_connection.db_connection;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import manager.ManagerPhase;
import manager.ViewStockInternalFrame;
import test.ViewAnalysisInternalFrame;
/**
 *
 * @author medo4
 */
public class StockManagerPhase extends javax.swing.JFrame {

    public void compositecoloringset(JPanel panel1,Color a,JPanel panel2,Color b)
    {
        panel1.setBackground(a);
        panel2.setBackground(b);
      
    }
    Color Default,Clicked;
    public StockManagerPhase() {
        initComponents();
        //setting icon on desktop bar 
        Image icon=new ImageIcon(this.getClass().getResource("/bill2.png")).getImage();
       this.setIconImage(icon);
       
       
        Default=new Color(255,255,255);
         Clicked=new Color(51,204,255);
           try {           
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ManagerPhase.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setResizable(false);
       
       
        //setting label and id for the cashier who logged in
          id_label.setText(get_StockManager_id()+" ");  //ID set;
          
          
           db_connection c= new db_connection();
           Connection conn=db_connection.connect();
           String query = "SELECT name FROM employee where employee_id=?";
            PreparedStatement stmt;
             ResultSet rs;
           
           
          
           
        try {
            stmt = conn.prepareStatement(query);
            stmt.setString(1,get_StockManager_id()+"");
            rs = stmt.executeQuery();
            if(rs.next())
            {
                String key=rs.getString("name");
                key=key.substring(0,1).toUpperCase()+key.substring(1);
                name_label.setText(key);
            }
        
            
        } catch (SQLException ex) {
            Logger.getLogger(CashierPhase.class.getName()).log(Level.SEVERE, null, ex);
        }
          
       
       
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lab = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        managestocklabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        viewanalysislabel = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        labelbutton = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name_label2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1076, 588));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab.setBackground(new java.awt.Color(255, 255, 255));
        lab.setFont(new java.awt.Font("The Bold Font", 1, 36)); // NOI18N
        lab.setForeground(new java.awt.Color(255, 255, 255));
        lab.setText("Manager");
        lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labMouseExited(evt);
            }
        });
        jPanel1.add(lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 50));

        lab2.setBackground(new java.awt.Color(255, 255, 255));
        lab2.setFont(new java.awt.Font("The Bold Font", 1, 36)); // NOI18N
        lab2.setForeground(new java.awt.Color(255, 255, 255));
        lab2.setText("Stock ");
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab2MouseExited(evt);
            }
        });
        jPanel1.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 410, 60));

        lab1.setBackground(new java.awt.Color(255, 255, 255));
        lab1.setFont(new java.awt.Font("The Bold Font", 1, 36)); // NOI18N
        lab1.setForeground(new java.awt.Color(0, 204, 255));
        lab1.setText("MENU");
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab1MouseExited(evt);
            }
        });
        jPanel1.add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        managestocklabel.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        managestocklabel.setForeground(new java.awt.Color(60, 110, 113));
        managestocklabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managestocklabel.setText("Manage Stock");
        managestocklabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managestocklabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managestocklabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managestocklabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managestocklabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                managestocklabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managestocklabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managestocklabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        viewanalysislabel.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        viewanalysislabel.setForeground(new java.awt.Color(60, 110, 113));
        viewanalysislabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewanalysislabel.setText("View Analysis");
        viewanalysislabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewanalysislabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewanalysislabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewanalysislabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewanalysislabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewanalysislabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewanalysislabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewanalysislabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 50));

        kGradientPanel2.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 102, 102));
        kGradientPanel2.setkGradientFocus(200);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 102, 102));
        kGradientPanel2.setMaximumSize(new java.awt.Dimension(800, 800));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelbutton.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        labelbutton.setForeground(new java.awt.Color(255, 255, 255));
        labelbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logoutversmall.png"))); // NOI18N
        labelbutton.setText("LOG OUT");
        labelbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelbuttonMouseExited(evt);
            }
        });
        kGradientPanel2.add(labelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 190, 50));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8-management-100.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 100));

        id.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        id.setForeground(new java.awt.Color(0, 204, 255));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("ID :");
        id.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                idMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                idMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idMousePressed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, 60));

        id_label.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        id_label.setForeground(new java.awt.Color(255, 255, 255));
        id_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_label.setText("Manager ID");
        id_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        id_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        id_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                id_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                id_labelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                id_labelMousePressed(evt);
            }
        });
        jPanel1.add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 150, 40));

        name_label.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        name_label.setForeground(new java.awt.Color(255, 255, 255));
        name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_label.setText("Manager Name");
        name_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        name_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        name_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                name_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                name_labelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                name_labelMousePressed(evt);
            }
        });
        jPanel1.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 220, 30));

        name_label2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        name_label2.setForeground(new java.awt.Color(0, 204, 255));
        name_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_label2.setText("Hello");
        name_label2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        name_label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        name_label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                name_label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                name_label2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                name_label2MousePressed(evt);
            }
        });
        jPanel1.add(name_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 50));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 240, 720));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/stock manager phase image.jpg"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        kGradientPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, 930, 758));
        jDesktopPane1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseEntered
        Color a=new Color(51,0,204) ;
        lab.setForeground(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_labMouseEntered

    private void labMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMouseExited
        lab.setForeground(Color.WHITE);
    }//GEN-LAST:event_labMouseExited

    private void lab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lab2MouseEntered

    private void lab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lab2MouseExited

    private void lab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lab1MouseEntered

    private void lab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lab1MouseExited

    private void viewanalysislabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewanalysislabelMouseClicked
        compositecoloringset(jPanel3,Clicked,jPanel2,Default);
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        ViewAnalysisInternalFrame view=new ViewAnalysisInternalFrame();
        jDesktopPane1.add(view).setVisible(true);
    }//GEN-LAST:event_viewanalysislabelMouseClicked

    private void viewanalysislabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewanalysislabelMouseEntered
    Color a=new Color(51,0,204) ;
     viewanalysislabel.setForeground(a);    
    }//GEN-LAST:event_viewanalysislabelMouseEntered

    private void viewanalysislabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewanalysislabelMouseExited
        viewanalysislabel.setForeground(new Color(0,204,0));
    }//GEN-LAST:event_viewanalysislabelMouseExited

    private void viewanalysislabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewanalysislabelMousePressed
        
      

    }//GEN-LAST:event_viewanalysislabelMousePressed

    private void managestocklabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managestocklabelMouseClicked
        compositecoloringset(jPanel2,Clicked,jPanel3,Default);
        StockManagerInternalFrame obj=new StockManagerInternalFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_managestocklabelMouseClicked

    private void managestocklabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managestocklabelMouseEntered
      
          Color a=new Color(51,0,204) ;
        managestocklabel.setForeground(a);
    }//GEN-LAST:event_managestocklabelMouseEntered

    private void managestocklabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managestocklabelMouseExited
       managestocklabel.setForeground(new Color(0,204,0));
    }//GEN-LAST:event_managestocklabelMouseExited

    private void managestocklabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managestocklabelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_managestocklabelMousePressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       compositecoloringset(jPanel2,Clicked,jPanel3,Default);
       
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
      compositecoloringset(jPanel3,Clicked,jPanel2,Default);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void labelbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbuttonMouseClicked

        login obj=new login();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_labelbuttonMouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void labelbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbuttonMouseEntered
         Color a=new Color(51,0,204) ;
         labelbutton.setForeground(a);
    }//GEN-LAST:event_labelbuttonMouseEntered

    private void labelbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbuttonMouseExited
        labelbutton.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelbuttonMouseExited

    private void idMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_idMouseEntered

    private void idMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_idMouseExited

    private void idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMousePressed

    private void id_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_labelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_id_labelMouseEntered

    private void id_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_labelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_id_labelMouseExited

    private void id_labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_labelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_labelMousePressed

    private void name_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_labelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_name_labelMouseEntered

    private void name_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_labelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_name_labelMouseExited

    private void name_labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_labelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_labelMousePressed

    private void name_label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_label2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_name_label2MouseEntered

    private void name_label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_label2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_name_label2MouseExited

    private void name_label2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_label2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_label2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagerPhase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagerPhase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JLabel id_label;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel labelbutton;
    private javax.swing.JLabel managestocklabel;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_label2;
    private javax.swing.JLabel viewanalysislabel;
    // End of variables declaration//GEN-END:variables
}
